### ISSUE TITLE
Dados de acesso - senha

### ISSUE THREAD

**Issue by oliveiralex** [JoaoOtavioSegantini/ds-movieflix#1]
Olá João, tudo bem?

Meu nome é Alexandre e estou corrigindo o seu trabalho. Gostaria de saber quais os dados de usuário e senha. Tentei o usuário "bob@gmail.com" e a senha 123456, porém deu inválido. Poderia baixar o seu projeto, da forma como você enviou e fazer um teste e verificar os dados do usuário? Lembrando que eu vou executar com o perfil de teste.

Peço que você verifique e por gentileza, reenvie o seu trabalho.

Abraço e bons estudos

**Comment by JoaoOtavioSegantini** [comment]
É estranho por que eu estou conseguindo acessar por aqui com esses dados, mas, pelo visto, por algum motivo, o backend não está sendo atualizado aqui no git corretamente. Mas já corrigi esse problema. Obrigado pela atenção!

**Comment by JoaoOtavioSegantini** [comment]
Trabalho quase concluído, só falta implementar um sistema de recomendações para ficar do jeito que quero...
